packages:
  # all packages in direct subdirs of client/
  - 'client/**'
  # all packages in subdirs of components/
  - 'components/**'
  # all packages in subdirs of utils/
  - 'utils/**'
  # all packages in subdirs of services/
  - 'services/**'
  # all packages in subdirs of pages/
  # exclude packages that are inside test directories
  - '!**/test/**'